http:
  maxTotal: 100 #最大连接数
  defaultMaxPerRoute: 20 #并发数
  connectTimeout: 2000 #创建连接的最长时间
  connectionRequestTimeout: 5000 #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  staleConnectionCheckEnabled: true #提交请求前测试连接是否可用

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.138.143:3306/autoium?characterEncoding=UTF-8&&serverTimezone=GMT%2B8
    # 武仪人
#    username: wuyiren
#    password: lengtong5655
    # 王子健
#    username: wzj123
#    password: wzj123
    # 陈涵
#    username: ibn5100
#    password: 114514
    # 吕帅慷
    username: lsk2020
    password: lsk2020
server:
  port: 8888

#返回json的全局时间格式
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:run/autoium/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
